### ISSUE TITLE
Force a timeout on requests to prevent pulse from getting stuck when a RPM fails to respond

### ISSUE THREAD

**Issue by jwindmuller** [rpmsoftware/rpm-pulse#8]
Today's [pulse outage](https://docs.google.com/document/d/1ex0DX6WPiagO8F3DtnFs3xOnkARMLoKANxReJeuOpXc/edit?usp=sharing) was caused by a server containing a couple of subscribers was turned off and RPM would never send a response.

On the pulse side let's add and enforce a timeout on the requests to EvaluateNextReminders to prevent pulse from getting stuck waiting for a response that never comes.

**Comment by rpmjade** [comment]
I agree
